runtime: java
runtime_config:
    operating_system: "ubuntu22"
    runtime_version: "21"
env: flex
service: default
instance_class: F2
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
entrypoint: java -jar target/madgridapi-0.0.1-SNAPSHOT.jar
